version: '3'
services: 
  postgresSQL:
    image: postgres:12
    #container_name: BD_TEST:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - "C:/backups:/backups"
volumes:
  postgres-data:
    driver: local
  postgres-backups:
    driver: local

networks:
  postgres_network: