version: '3.0'
services: 
  postgresSQL:
    image: postgres:12
    container_name: BD-TEST
    environment:
      POSTGRES_BD: bd_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - postgres-backups:/backups

volumes:
postgres-data:
postgres-backups:
